seed: 12345
output: null

trainer:
  accelerator: "gpu"
  devices: 1
  max_epochs: 10
  precision: 16
  gradient_clip_val: 1.0
  val_check_interval: 1.0
  resume_from_checkpoint: null
  accumulate_grad_batches: 1
  num_sanity_val_steps: 0

# data module
data:
  debug: True
  batch_size: 8
  num_workers: 5
  train_dir: null
  trial_dir: '/userfiles/ikesen16/data/vwsd/trial'

# hydra-specific
hydra:
  run:
    dir: .

defaults:
  - _self_
  - override hydra/job_logging: disabled